### ISSUE TITLE
support HLS output

### ISSUE THREAD

**Issue by flavioribeiro** [snickers/snickers#41]
refs #40

we should group all HLS presets of a given job in a single output with a master playlist that maps the levels to the presets.

**Comment by brkattk** [comment]
General playlist output would be nice. That way you could handle MPEG-Dash as well.

**Comment by flavioribeiro** [comment]
I made some tests with [this](https://github.com/iliya-gr/mediasegmenter) project and everything works well. I think we should port the [segmenter](https://github.com/iliya-gr/mediasegmenter/blob/master/segmenter.c) to Go and send a PR to [gmf](https://github.com/3d0c/gmf). This issue should only cover one preset for now, we can think/discuss about how to handle multiple levels after that.

**Comment by flavioribeiro** [comment]
we should use [hlssegmenter](https://github.com/snickers/hlssegmenter) for this. For the first support, I wonder if we can just generate a `h264/mp4` video from the given preset using [ffmpeg](https://github.com/snickers/snickers/blob/master/encoders/ffmpeg.go) and call `hlssegmenter.Segment()` after that.

**Comment by bradleyfalzon** [comment]
Just a note, ffmpeg can segment into hls itself, no need for an external tool.

Such as:

```ffmpeg -t 30 -re -f lavfi -i testsrc=size=640x360:rate=25 -s 640x360 -b:v  300k -maxrate 300k -bufsize 300k -c:v libx264 -pix_fmt yuv420p -profile:v main -level 3.1 -bf 0 -g 50 -keyint_min 50 -sc_threshold 0 -c:a aac -ac 2 -ar 48000 -strict -2 -ab 96k -f hls -hls_time 4 -hls_list_size 0 media.m3u8```

There maybe limitations as to why you didn't choose to do it this way, and if so, my apologies. Note it also doesn't support fMP4.

**Comment by flavioribeiro** [comment]
hey @bradleyfalzon thanks for your comment!

@marzagao pointed me to the FFmpeg native [implementation](https://github.com/FFmpeg/FFmpeg/blob/3e5d27d7a7350e096eac9f8999d02bf48c3b3a69/libavformat/hlsenc.c) before but I'm wondering if I should change the libav calls on [hls/segmenter](https://github.com/snickers/hls/blob/master/segmenter/segmenter.go) or not. Honestly, I think I'm gonna go with the initial approach and them I'll see if it's better to port the hls/segmenter to the native implementation.

**Comment by bradleyfalzon** [comment]
Ah yes if the works already done, I just wasn't sure if this was already shelling out to run ffmpeg, then it could do it all in the one command - perhaps I misread. Happy to leave, thanks for the response.

**Comment by flavioribeiro** [comment]
@bradleyfalzon yeah I'm trying to avoid triggering command line jobs, calling the method calls instead. IMHO It's easier to keep track of what's happening. Anyway, thanks for the input on this!
